name: Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Clear Python cache
      run: |
        find . -type d -name "__pycache__" -exec rm -rf {} + || true
        find . -name "*.pyc" -delete || true
        find . -name "*.pyo" -delete || true
        
    - name: Clear linter caches
      run: |
        rm -rf ~/.cache/black || true
        rm -rf ~/.cache/flake8 || true
        rm -rf ~/.cache/isort || true
        rm -rf ./.mypy_cache || true
        
    - name: Install dependencies (no cache)
      run: |
        python -m pip install --upgrade pip --no-cache-dir
        pip install --no-cache-dir flake8 black==25.1.0 isort
        if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
        
    - name: Run flake8
      run: |
        flake8 coder/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Check formatting with black
      run: |
        echo "Black version:" && black --version
        echo "Running black --check with diff output..."
        black --check --diff coder/ tests/
        
    - name: Check import order with isort
      run: |
        isort --check-only --profile black coder/ tests/ 